backend:
  name: git-gateway

local_backend: true

media_folder: static/assets
public_folder: /assets

collections:
  - label: Site Info
    name: siteInfo
    files:
      - label: About
        name: about
        file: src/content/about.md
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: about }
          - label: About SANDALBOYZ
            name: about
            hint: Say something about SANDALBOYZ
            widget: text
      - label: Pop Up
        name: popup
        file: src/content/popup.md
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: popup }
          - label: Enabled
            name: enabled
            widget: boolean
          - label: Label
            name: label
            widget: string
            required: false
          - label: Title
            name: title
            widget: string
            required: false
          - label: Description
            name: description
            widget: markdown
            required: false
          - label: Image
            name: image
            widget: image
            required: false
          - label: Popup Expiration Time
            name: expires
            widget: number
            default: 2
            valueType: int
            min: 1
            max: 365
            hint: Enter value in number of days (i.e. 2 for 2 days, etc.)
      - label: Landing Page Hero
        name: fullHero
        file: src/content/fullHero.md
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: fullHero }
          - label: Label
            name: label
            widget: string
            required: false
          - label: Title
            name: title
            widget: string
          - label: Call to Action
            name: callToAction
            widget: string
          - label: Desktop Image
            name: desktopImage
            widget: image
            hint: Use a square 1w x 1h (1680px minimum) image ratio
          - label: Mobile Image
            name: mobileImage
            widget: image
            hint: Use 375w x 812h image ratio (https://markcormack.co.uk/iphone-x-safari-browser-chrome-guide/)
  - label: Pages
    name: pages
    files:
      - label: FAQ
        name: faq
        file: src/content/faq.md
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: faq }
          - { label: Title, name: title, widget: string, default: FAQ }
          - label: Questions
            name: questions
            widget: list
            fields:
              - { label: Question, name: question, widget: string }
              - { label: Answer, name: answer, widget: markdown }
      - label: Privacy
        name: privacy
        file: src/content/privacy.md
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: privacy }
          - { label: Title, name: title, widget: string, default: Privacy Policy }
          - { label: Body, name: body, widget: markdown }
      - label: Returns
        name: returns
        file: src/content/returns.md
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: returns }
          - { label: Title, name: title, widget: string, default: Shipping and Returns }
          - { label: Body, name: body, widget: markdown }
      - label: Terms
        name: terms
        file: src/content/terms.md
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: terms }
          - { label: Title, name: title, widget: string, default: Terms and Conditions }
          - { label: Body, name: body, widget: markdown }
