# backend is defined in src/cms/cms.js

media_folder: static/assets

public_folder: /assets

collections:
  - label: Stories
    name: stories
    folder: src/pages/stories
    create: true
    fields:
      - { label: Template Key, name: templateKey, widget: hidden, default: story }
      - { label: Title, name: title }
      - { label: Author, name: author, widget: string, default: SANDALBOYZ }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Hero Image, name: hero, widget: image }
      - { label: Body, name: body, widget: markdown }
      - { label: Feature on Landing Page Hero, name: landingFeatured, widget: boolean, required: false }
      - { label: Feature on Stories Page Hero, name: storiesFeatured, widget: boolean, required: false }
      - { label: Tags, name: tags, widget: list, required: false }

  - label: Site Info
    name: siteInfo
    files:
      - label: About
        name: about
        file: src/content/about.md
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: about }
          - label: About SANDALBOYZ,
            name: about,
            hint: Say something about SANDALBOYZ,
            widget: text
