# backend is defined in src/cms/cms.js

media_folder: static/assets

public_folder: /assets

collections:
  - label: Stories
    name: stories
    folder: src/pages/stories
    create: true
    fields:
      - { label: Template Key, name: templateKey, widget: hidden, default: story }
      - { label: Title, name: title }
      - label: Author(s)
        name: authors
        widget: list
        field: { label: Author, name: author }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Hero Image, name: hero, widget: image }
      - { label: Lede, name: lede, widget: text, required: false }
      - { label: Feature on Landing Page Hero, name: landingFeatured, widget: boolean, required: false }
      - { label: Feature on Stories Page Hero, name: storiesFeatured, widget: boolean, required: false }
      - { label: Tags, name: tags, widget: list, required: false }
      - label: Sections
        name: sections
        widget: list
        types:
          - label: Text Block
            name: text
            widget: object
            fields:
              - { label: Body, name: body, widget: markdown }
          - label: Image Block
            name: image
            widget: object
            fields:
              - label: Image Type
                name: imageType
                widget: select
                options:
                  - { label: Fullwidth Image, value: fullWidth }
                  - { label: Split Image, value: split }
                  - { label: Two-Thirds Image, value: twoThirds }
              - label: Images
                name: images
                widget: list
                hint: Add one (1) image for Fullwidth and Two-Thirds Image Blocks, and two (2) images for the Split Image Block
                field: { label: Image, name: image, widget: image }
              - label: Caption
                name: caption
                widget: string
                required: false
                hint: Only displayed for the Split Image Block

  - label: Site Info
    name: siteInfo
    files:
      - label: About
        name: about
        file: src/content/about.md
        fields:
          - { label: Template Key, name: templateKey, widget: hidden, default: about }
          - label: About SANDALBOYZ,
            name: about,
            hint: Say something about SANDALBOYZ,
            widget: text
